[package]
name = "rust-nn"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
rand = "0.8.4"
flate2 = "1.0"
byteorder = "1.4"
ndarray = { version = "0.16.0", default-features = false, features = [
    "rayon",
    "matrixmultiply-threading",
] }
